image:
  name: traefik
  tag: "2.6.1"

ingressClass:
  enabled: true

deployment:
  enabled: true
  kind: Deployment
  replicas: 2
  imagePullSecrets: []

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec: 
    externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ACM-cert>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: "load-balancer-logs"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "traefik-internal"

#custom:
dashboard:
  host: <traefik-internal-dashboard>

nodepool: general